title: Matthew McGuigan, BSc, MSc.
name: Matthew McGuigan
email: matthew.g.mcguigan@gmail.com
description: I am a Computer Science PhD student at the University of Exeter.

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: My PhD Project
project_one_description: My PhD involves the estimation of an objectâ€™s shape, reflectance and surface topography from photographs using machine learning and artificial intelligence approaches.
project_one_url: http://emps.exeter.ac.uk/computer-science/staff/mm757 
project_one_icon: location_on

project_two: Solar Eclipse TV Interview
project_two_description: I was contacted for an interview and asked to explain how to image the 2015 solar eclipse. I also discussed some astrophotograpy which I had posted online. 
project_two_url: https://www.youtube.com/watch?v=VR57efH0Kfs&t=8s
project_two_icon: photo_camera

project_three: RTI Group at Exeter
project_three_description: The group in which I am a postgraduate student consists of a range of personnel from various disciplines including computer science, natrual science and material science.
project_three_url: https://sites.google.com/a/exeter.ac.uk/rti/home
project_three_icon: restaurant

project_four: Photography
project_four_description: A few of my photographs
project_four_url: https://photos.app.goo.gl/JDyzvJJ9JCwH9u27A
project_four_icon: hotel

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
#Matlab, R, Python, C#, C++, Javascript, LabVIEW, Unity, Blender, Github.


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: SEE MORE

#github: _
#medium: _

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

google_analytics_tracking_id: UA-121110956-1

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
